const express=require('express');const cors=require('cors');const path=require('path');const fs=require('fs');const axios=require('axios');const cheerio=require('cheerio');require('dotenv').config();
const app=express();const PORT=Number(process.env.PORT||5000);const HOST=process.env.HOST||'0.0.0.0';const ROOT=__dirname;const PUBLIC=path.join(ROOT,'public');const DATA_DIR=path.join(ROOT,'data');const DATA_FILE=path.join(DATA_DIR,'raksha-data.json');
app.use(cors({origin:true,credentials:true}));app.use(express.json({limit:'5mb'}));app.use(express.static(PUBLIC));
const clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,n));const finite=n=>Number.isFinite(Number(n));const now=()=>new Date().toISOString();
const dist=(a,b,c,d)=>{const r=Math.PI/180,dl=(c-a)*r,do_=(d-b)*r,x=Math.sin(dl/2)**2+Math.cos(a*r)*Math.cos(c*r)*Math.sin(do_/2)**2;return 6371*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));};
function initial(){return{reports:[],shelters:[
{id:1,name:'Central Community Shelter',type:'Shelter',address:'Community Emergency Centre',state:'Madhya Pradesh',district:'Indore',latitude:22.7196,longitude:75.8577,capacity:500,occupied:320,phone:'112',active:true},
{id:2,name:'City Hospital Emergency',type:'Hospital',address:'Government Emergency Medical Centre',state:'Madhya Pradesh',district:'Indore',latitude:22.7258,longitude:75.8656,capacity:250,occupied:178,phone:'108',active:true},
{id:3,name:'Sector 5 Rescue Unit',type:'Rescue',address:'Emergency Rescue Station',state:'Madhya Pradesh',district:'Indore',latitude:22.7046,longitude:75.8753,capacity:20,occupied:8,phone:'112',active:true},
{id:4,name:'North Relief Centre',type:'Shelter',address:'Temporary Relief Centre',state:'Madhya Pradesh',district:'Indore',latitude:22.7500,longitude:75.8250,capacity:300,occupied:180,phone:'112',active:true},
{id:5,name:'Riverside Relief Centre',type:'Shelter',address:'Flood Relief Point',state:'Madhya Pradesh',district:'Indore',latitude:22.7000,longitude:75.8850,capacity:500,occupied:472,phone:'112',active:true}],cache:{}}}
function load(){fs.mkdirSync(DATA_DIR,{recursive:true});if(!fs.existsSync(DATA_FILE))save(initial());try{return JSON.parse(fs.readFileSync(DATA_FILE,'utf8'))}catch{return initial()}}
function save(x){fs.mkdirSync(DATA_DIR,{recursive:true});fs.writeFileSync(DATA_FILE,JSON.stringify(x,null,2))}
const store=load();
function cacheSet(k,v){store.cache[k]={value:v,updatedAt:now()};save(store)}function cacheGet(k){return store.cache[k]||null}
async function weather(lat,lon){const key=`weather:${Number(lat).toFixed(3)}:${Number(lon).toFixed(3)}`;const url=`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,relative_humidity_2m,apparent_temperature,precipitation,weather_code,wind_speed_10m,pressure_msl&hourly=precipitation,precipitation_probability,wind_speed_10m,weather_code&forecast_days=2&timezone=auto`;try{const r=await axios.get(url,{timeout:12000});cacheSet(key,r.data);return{live:true,offline:false,source:'Open-Meteo',data:r.data,fetchedAt:now()}}catch(e){const c=cacheGet(key);return{live:false,offline:!!c,source:'Open-Meteo',data:c?.value||null,fetchedAt:c?.updatedAt||null,message:c?'Showing cached weather.':'Weather source unavailable.'}}}
async function earthquakes(){const key='earthquakes';try{const r=await axios.get('https://riseq.seismo.gov.in/riseq/earthquake/recent_earthquake',{timeout:15000,headers:{'User-Agent':'RAKSHA/1.0','Accept':'text/html'}});const $=cheerio.load(String(r.data)),out=[];$('table tr').each((_,tr)=>{const c=$(tr).find('td').map((__,td)=>$(td).text().trim()).get();if(c.length<5)return;const lat=Number(c[1]),lon=Number(c[2]),depth=Number(c[3]),mag=Number(c[4]);if(!finite(lat)||!finite(lon)||!finite(mag))return;out.push({originTime:c[0]||null,latitude:lat,longitude:lon,depthKm:finite(depth)?depth:null,magnitude:mag,region:c[5]||'',location:c[6]||'',source:'NCS'})});const uniq=out.filter((x,i,a)=>a.findIndex(y=>y.originTime===x.originTime&&y.latitude===x.latitude&&y.longitude===x.longitude&&y.magnitude===x.magnitude)===i).slice(0,100);cacheSet(key,uniq);return{live:true,offline:false,source:'NCS',data:uniq,fetchedAt:now()}}catch(e){const c=cacheGet(key);return{live:false,offline:!!c,source:'NCS',data:c?.value||[],fetchedAt:c?.updatedAt||null,message:c?'Showing cached earthquake data.':'NCS source unavailable.'}}}
function wrisk(w){const c=w?.data?.current;if(!c)return{score:0,reasons:[]};let s=0,r=[];const p=Number(c.precipitation||0),wind=Number(c.wind_speed_10m||0),code=Number(c.weather_code??-1);if(p>=30){s+=Math.min(50,p*.6);r.push(`Current precipitation is ${p} mm.`)}else if(p>=10){s+=Math.min(25,p*.8);r.push(`Current precipitation is ${p} mm.`)}if(wind>=50){s+=30;r.push(`Wind speed is ${wind} km/h.`)}else if(wind>=30){s+=15;r.push(`Wind speed is ${wind} km/h.`)}if([95,96,99].includes(code)){s+=30;r.push('Severe-weather code is active.')}else if([65,67,80,81,82].includes(code)){s+=20;r.push('Heavy-rain weather code is active.')}return{score:clamp(Math.round(s)),reasons:r}}
function erisk(lat,lon,eq){let best=0,r=[];for(const e of eq||[]){if(!finite(e.latitude)||!finite(e.longitude)||!finite(e.magnitude))continue;const d=dist(lat,lon,e.latitude,e.longitude);let s=e.magnitude>=6?95:e.magnitude>=5?80:e.magnitude>=4?55:e.magnitude>=3?30:10;if(d>300)s*=.1;else if(d>200)s*=.2;else if(d>100)s*=.4;else if(d>50)s*=.65;else if(d>25)s*=.85;s=Math.round(clamp(s));best=Math.max(best,s);if(s>=35)r.push(`Magnitude ${e.magnitude} earthquake about ${Math.round(d)} km away.`)}return{score:best,reasons:r}}
function rrisk(lat,lon){let best=0,r=[];for(const x of store.reports.filter(x=>x.status!=='resolved'&&finite(x.latitude)&&finite(x.longitude)).slice(0,100)){const d=dist(lat,lon,x.latitude,x.longitude),p=d<2?1:d<5?.65:d<10?.3:0,s=Math.round((Number(x.severity)||0)*p);best=Math.max(best,s);if(s>=35)r.push(`Citizen report nearby: ${x.type}.`)}return{score:best,reasons:r}}
async function buildRisk(lat,lon){const[w,e]=await Promise.all([weather(lat,lon),earthquakes()]);const a=wrisk(w),b=erisk(lat,lon,e.data),c=rrisk(lat,lon),score=Math.round(clamp(Math.max(a.score,b.score,c.score)));const level=score>=80?'CRITICAL':score>=60?'HIGH':score>=35?'MODERATE':'LOW';return{risk:{score,level,generatedAt:now()},weather:w,earthquakes:e,reasons:[...a.reasons,...b.reasons,...c.reasons].slice(0,8)}}
function zones(lat,lon,score){return[{id:'A',name:'Primary Impact Zone',lat,lon,radius:1800,score:clamp(score+8),type:'PRIMARY'},{id:'B',name:'High-Risk Buffer',lat:lat+.018,lon:lon+.014,radius:1300,score:clamp(score-4),type:'BUFFER'},{id:'C',name:'Watch Zone',lat:lat-.022,lon:lon-.018,radius:1100,score:clamp(score-18),type:'WATCH'}]}
function shelters(lat,lon){return store.shelters.filter(x=>x.active).map(x=>({...x,distanceKm:finite(lat)&&finite(lon)?Number(dist(lat,lon,x.latitude,x.longitude).toFixed(2)):null,available:Math.max(0,x.capacity-x.occupied)})).sort((a,b)=>(a.distanceKm??99999)-(b.distanceKm??99999))}
function alerts(r,reasons){return[{level:r.score>=80?'CRITICAL':r.score>=60?'WARNING':r.score>=35?'WATCH':'INFO',title:r.score>=80?'Immediate risk level is critical':r.score>=60?'High disaster risk detected':r.score>=35?'Moderate risk detected':'No critical hazard detected',message:reasons[0]||'RAKSHA is continuing to monitor current conditions.'}]}
app.get('/api/health',(req,res)=>res.json({name:'RAKSHA',status:'online',version:'1.0.0',storage:'JSON file',time:now()}));
app.get('/api/dashboard',async(req,res)=>{const lat=finite(req.query.lat)?Number(req.query.lat):22.7196,lon=finite(req.query.lng)?Number(req.query.lng):75.8577;try{const d=await buildRisk(lat,lon),ss=shelters(lat,lon),reports=store.reports.length;res.json({project:'RAKSHA',generatedAt:now(),location:{lat,lon},risk:d.risk,reasons:d.reasons,weather:d.weather,earthquakes:{count:d.earthquakes.data.length,data:d.earthquakes.data,live:d.earthquakes.live},zones:zones(lat,lon,d.risk.score),shelters:ss,reportsCount:reports,alerts:alerts(d.risk,d.reasons),system:{online:true,storage:'JSON'}})}catch(e){console.error(e);res.status(500).json({error:'Dashboard generation failed.'})}});
app.get('/api/weather',async(req,res)=>res.json(await weather(Number(req.query.lat)||22.7196,Number(req.query.lng)||75.8577)));
app.get('/api/earthquakes',async(req,res)=>res.json(await earthquakes()));
app.get('/api/risk',async(req,res)=>{const lat=Number(req.query.lat),lon=Number(req.query.lng);if(!finite(lat)||!finite(lon))return res.status(400).json({error:'lat and lng are required'});res.json(await buildRisk(lat,lon))});
app.get('/api/zones',async(req,res)=>{const lat=Number(req.query.lat)||22.7196,lon=Number(req.query.lng)||75.8577,d=await buildRisk(lat,lon);res.json({location:{lat,lon},risk:d.risk,zones:zones(lat,lon,d.risk.score)})});
app.get('/api/shelters',(req,res)=>{const lat=finite(req.query.lat)?Number(req.query.lat):null,lon=finite(req.query.lng)?Number(req.query.lng):null;res.json({count:shelters(lat,lon).length,data:shelters(lat,lon)})});
app.get('/api/alerts',async(req,res)=>{const lat=Number(req.query.lat)||22.7196,lon=Number(req.query.lng)||75.8577,d=await buildRisk(lat,lon);res.json({alerts:alerts(d.risk,d.reasons),updatedAt:now()})});
app.post('/api/reports',(req,res)=>{const x={id:Date.now(),type:req.body?.type||'Other',description:req.body?.description||'',latitude:finite(req.body?.latitude)?Number(req.body.latitude):null,longitude:finite(req.body?.longitude)?Number(req.body.longitude):null,severity:clamp(Number(req.body?.severity)||50),status:'pending',created_at:now()};store.reports.unshift(x);save(store);res.status(201).json({success:true,id:x.id,message:'Incident received and added to the response queue.',report:x})});
app.get('/api/reports',(req,res)=>res.json({count:store.reports.length,data:store.reports.slice(0,100)}));
app.post('/api/assistant',async(req,res)=>{const message=String(req.body?.message||'').trim(),lat=finite(req.body?.lat)?Number(req.body.lat):22.7196,lon=finite(req.body?.lng)?Number(req.body.lng):75.8577;if(!message)return res.status(400).json({error:'message is required'});const d=await buildRisk(lat,lon),near=shelters(lat,lon)[0],q=message.toLowerCase();let answer;if(q.includes('shelter'))answer=`Nearest verified facility: ${near?.name||'No shelter available'}${near?.distanceKm!=null?` (${near.distanceKm} km)`:''}. Available capacity: ${near?Math.max(0,near.capacity-near.occupied):'unknown'}.`;else if(q.includes('route')||q.includes('road'))answer=`Current RAKSHA risk is ${d.risk.score}/100 (${d.risk.level}). Avoid the primary impact zone and follow the route shown in the Evacuation screen.`;else if(q.includes('safe')||q.includes('risk'))answer=`Current RAKSHA risk is ${d.risk.score}/100 (${d.risk.level}). ${d.reasons[0]||'No major contributing hazard signal is currently available.'}`;else answer=`RAKSHA currently rates the selected area ${d.risk.score}/100 (${d.risk.level}). I can explain the risk, find the nearest shelter, or help with evacuation.`;res.json({answer,risk:d.risk,reasons:d.reasons,sources:{weather:d.weather.live?'LIVE':'CACHED',earthquakes:d.earthquakes.live?'LIVE':'CACHED'}})});
app.get('/api/route',async(req,res)=>{const slat=Number(req.query.slat),slon=Number(req.query.slon),dlat=Number(req.query.dlat),dlon=Number(req.query.dlon);if([slat,slon,dlat,dlon].some(n=>!finite(n)))return res.status(400).json({error:'slat, slon, dlat and dlon are required'});try{const url=`https://router.project-osrm.org/route/v1/driving/${slon},${slat};${dlon},${dlat}?overview=full&geometries=geojson&alternatives=true&steps=false`,r=await axios.get(url,{timeout:12000}),best=r.data?.routes?.[0];if(!best)throw new Error('No route');res.json({source:'OSRM',distanceKm:Number((best.distance/1000).toFixed(2)),durationMin:Math.max(1,Math.round(best.duration/60)),geometry:best.geometry})}catch(e){const d=dist(slat,slon,dlat,dlon);res.json({source:'FALLBACK',distanceKm:Number(d.toFixed(2)),durationMin:Math.max(1,Math.round(d/35*60)),geometry:{type:'LineString',coordinates:[[slon,slat],[dlon, dlat]]},warning:'Routing service unavailable; showing a direct fallback line.'})}});
app.get('/api/state',(req,res)=>res.json({name:'Madhya Pradesh',focus:'Indore',center:[22.9734,78.6569],bbox:[[21.1,74.0],[26.9,82.8]]}));
app.use((req,res)=>res.sendFile(path.join(PUBLIC,'index.html')));
app.listen(PORT,HOST,()=>console.log(`RAKSHA running at http://localhost:${PORT}`));
